service:
  apidocurl: http://localhost:8080/v2/api-docs
---
spring:
  config:
    activate:
      on-profile: public
service:
  apidocurl: http://localhost:8080/v2/api-docs?group=publicapi
---
spring:
  config:
    activate:
      on-profile: user
service:
  apidocurl: http://localhost:8080/v2/api-docs?group=userapi
---
spring:
  config:
    activate:
      on-profile: admin
service:
  apidocurl: http://localhost:8080/v2/api-docs?group=adminapi