serviceId: zoweapidoc
title: Zowe Apidoc
description: Zowe Apidoc sample application
baseUrl: https://localhost:8080/
serviceIpAddress: 127.0.0.1
preferIpAddress: false

homePageRelativeUrl: /greeting
statusPageRelativeUrl:
healthCheckRelativeUrl:

discoveryServiceUrls:
  - https://localhost:10011/eureka

routes:
  - gatewayUrl: api/v1
    serviceUrl: /

apiInfo:
  - apiId: com.jandadav.zoweapidoc
    version: 1.0.0
    gatewayUrl: api/v1
    swaggerUrl: http://localhost:8080/v2/api-docs
    doumentationUrl: http://


catalog:
  tile:
    id: zoweapidoc
    title: Zowe Apidoc
    description: Zowe Apidoc sample application
    version: 1.0.0

ssl:
  enabled: true
  verifySslCertificatesOfServices: true
  protocol: TLSv1.2
  keyAlias: localhost
  keyPassword: password
  keyStore: keys/localhost.keystore.p12
  keyStoreType: PKCS12
  keyStorePassword: password
  trustStore: keys/localhost.truststore.p12
  trustStoreType: PKCS12
  trustStorePassword: password